image: node

#below are the order of the stages in our pipeline
#some stages run 1 by 1 some run at the same time
stages:
  - build
  - test
  - deploy staging
  - test staging deployment
  - deploy production
  - test production deployment

#Global cache configuration
cache:
  key: ${CI_COMMIT_REF_SLUG} #this is a predefined variable to point at your current branch
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test
  image: alpine
  script:
    - test -f ./public/index.html
    - grep -q "gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve & #start the server using the production build port 9000
    - sleep 3 #add a command so that the server has some time to spin up before next command
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby" #download the contents of this website from the input and pass it into the grep
    #what tac is doing is making the grep wait until all the output is written from the curl

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: "http://medical-tin-staging.surge.sh"
  script:
    - echo "deploy staging"
    - npm install --global surge
    - surge --project ./public --domain medical-tin-staging.surge.sh
    
test staging deployment:
  stage: test staging deployment
  image: alpine
  script:
    - echo "test staging deployment"
    - curl "medical-tin.surge.sh" | tac | tac | grep "Gatsby"

deploy production:
  stage: deploy production
  environment:
    name: production
    url: "http://medical-tin-staging.surge.sh"
  script:
    - npm install --global surge
    - surge --project ./public --domain medical-tin.surge.sh

test production deployment:
  stage: test production deployment
  image: alpine
  cache: {}
  script:
    - apk add --no-cache curl
    - curl "medical-tin.surge.sh" | tac | tac | grep "Gatsby"
    - curl "medical-tin.surge.sh" | tac | tac | grep "$CI_COMMIT_SHORT_SHA"


